# Generated by Django 4.1.2 on 2024-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handler", "0003_contactus_product_availability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "verbose_name": "Company details",
                "verbose_name_plural": "Company details",
            },
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Contact Us", "verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Product images",
                "verbose_name_plural": "Product images",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="facebook_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="instagram_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="terms_and_conditions",
            field=models.TextField(
                default="Please read our terms and conditions carefully before using our services."
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="twitter_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
