# Generated by Django 4.1.2 on 2024-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handler", "0004_alter_company_options_alter_contactus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slide",
            field=models.ImageField(blank=True, null=True, upload_to="slider/"),
        ),
    ]
